# Generated by Django 3.1.7 on 2021-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_long_name', models.CharField(max_length=100)),
                ('college_short_name', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=100)),
                ('college_code', models.CharField(max_length=10)),
            ],
        ),
    ]
