# Generated by Django 3.1.7 on 2021-08-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegename', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collegename',
            table='college_name',
        ),
    ]
