# Generated by Django 3.2 on 2021-06-15 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
