# Generated by Django 3.2 on 2021-06-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('F', 'faculty'), ('S', 'student')], default='S', max_length=2),
        ),
    ]
