# Generated by Django 3.2 on 2021-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('1', 'STUDENT'), ('2', 'FACULTY')], default='2', max_length=7),
        ),
    ]
