# Generated by Django 3.1.7 on 2021-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.AddField(
            model_name='users',
            name='roles',
            field=models.CharField(choices=[('student', 'student'), ('faculty', 'faculty')], default='student', max_length=20),
        ),
    ]
