# Generated by Django 3.1.7 on 2021-06-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210617_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='roles',
        ),
    ]
