# Generated by Django 3.2 on 2021-06-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='usn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
