# Generated by Django 3.1.7 on 2021-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='cgpa',
            field=models.FloatField(default=6.0),
        ),
    ]
