# Generated by Django 3.2 on 2021-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=50),
        ),
    ]
