# Generated by Django 3.2 on 2021-06-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20210617_1315'),
        ('faculty', '0003_faculty_faculty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('comments', models.TextField()),
                ('elective_id', models.ForeignKey(db_column='elective_id', on_delete=django.db.models.deletion.CASCADE, to='electives.electives')),
                ('faculty_id', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
            options={
                'verbose_name_plural': 'faculty_ratings',
                'db_table': 'faculty_ratings',
            },
        ),
    ]
