# Generated by Django 3.1.7 on 2021-06-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty_Rating',
        ),
    ]
