# Generated by Django 3.1.7 on 2021-06-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_students_cgpa'),
        ('faculty', '0004_faculty_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('comments', models.TextField()),
                ('faculty_id', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
