# Generated by Django 3.1.7 on 2021-06-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ratings',
            table='ratings',
        ),
    ]
