# Generated by Django 3.1.7 on 2021-06-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20210617_1315'),
        ('ratings', '0002_auto_20210628_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='elective_id',
            field=models.ForeignKey(db_column='elective_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='electives.electives'),
        ),
    ]
