# Generated by Django 3.1.7 on 2021-06-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20210617_1315'),
        ('ratings', '0003_ratings_elective_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='elective_id',
            field=models.ForeignKey(db_column='elective_id', on_delete=django.db.models.deletion.CASCADE, to='electives.electives'),
        ),
    ]
