# Generated by Django 3.1.7 on 2021-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20210629_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='ratings',
            new_name='stars',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
