# Generated by Django 3.1.7 on 2021-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_full_name', models.CharField(max_length=50, unique=True)),
                ('branch_short_name', models.CharField(default=None, max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'db_table': 'branches',
            },
        ),
    ]
