# Generated by Django 3.2 on 2021-06-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electives',
            fields=[
                ('elective_id', models.AutoField(primary_key=True, serialize=False)),
                ('elective_name', models.CharField(max_length=70, unique=True)),
                ('elective_short_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'electives',
                'db_table': 'electives',
            },
        ),
        migrations.CreateModel(
            name='ElectiveSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='branches.branches')),
                ('elective_id', models.ForeignKey(db_column='elective_id', on_delete=django.db.models.deletion.CASCADE, to='electives.electives')),
                ('semester_id', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='semesters.semesters')),
            ],
            options={
                'verbose_name_plural': 'elective_semesters',
                'db_table': 'elective_semesters',
                'unique_together': {('elective_id', 'semester_id', 'branch_id')},
            },
        ),
    ]
