# Generated by Django 3.1.7 on 2021-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20210617_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electivedetails',
            old_name='introduction_video',
            new_name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='electivedetails',
            name='syllabus_pdf',
        ),
        migrations.AddField(
            model_name='electivedetails',
            name='introduction_video_id',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='electivedetails',
            name='syllabus_pdf_id',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='electives',
            name='elective_code',
            field=models.CharField(max_length=10),
        ),
    ]
