# Generated by Django 3.1.7 on 2021-07-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_auto_20210701_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electivedetails',
            old_name='introduction_video_id',
            new_name='introduction_video',
        ),
        migrations.RenameField(
            model_name='electivedetails',
            old_name='syllabus_pdf_id',
            new_name='syllabus_pdf',
        ),
    ]
