# Generated by Django 3.1.7 on 2021-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0004_auto_20210703_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivedetails',
            name='introduction_video',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='electivedetails',
            name='syllabus_pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
