# Generated by Django 3.1.7 on 2021-07-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0006_electiveselected'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='electiveselected',
            table='electiveSelected',
        ),
    ]
