# Generated by Django 3.1.7 on 2021-07-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0007_auto_20210704_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivedetails',
            name='elective_id',
            field=models.ForeignKey(db_column='elective_id', on_delete=django.db.models.deletion.CASCADE, to='electives.electives', unique=True),
        ),
    ]
