# Generated by Django 3.1.7 on 2021-07-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
        ('electives', '0009_auto_20210725_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommanderQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('subject_name', models.CharField(max_length=40)),
                ('semester_id', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='semesters.semesters')),
            ],
        ),
    ]
