# Generated by Django 3.1.7 on 2021-06-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
