# Generated by Django 3.1.7 on 2021-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20210613_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
